[package]
name = "openimageio-sys"
version = "0.1.0"
authors = ["Alexandre Bléron <alex.bleron@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "*"

[build-dependencies]
vcpkg = "0.2.11"
pkg-config = "0.3.16"
bindgen = "0.57.0"
cc = "1.0.66"
